
import __ASTRO_IMAGE_IMPORT_Z1IIUgz from "/src/images/danmurrayartist-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json";
import __ASTRO_IMAGE_IMPORT_LokdX from "/src/images/danmurrayartist-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json";
import __ASTRO_IMAGE_IMPORT_Z1DezM0 from "/src/images/skyarts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json";
import __ASTRO_IMAGE_IMPORT_Z1D1O0h from "/src/images/Jane Seated 2018 Acrylics on board 84cm x 135cm.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_Z2vgfLz from "/src/images/Andrew Seated - Acrylic on Board - 120cm x 120cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_1EunyO from "/src/images/Alan with Manson - Acrylic on Board - 84cm x 135cm - 2018.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_6nST9 from "/src/images/Eleaine - Acrylic on Board - 45cm x 65cm - 2020.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_Z20dRCP from "/src/images/John and Lyndsay Todd - Acrylic on Board - 91cm x  120cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_Z5jsxv from "/src/images/Mum in 6 Naast with view to Sron Dubh - Acrylic on Board - 98cm x 170cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_1ipsai from "/src/images/Mum in the afternoon light - Acrylic on Board -  23cm x 30cm - 2025.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_Z1QqU9G from "/src/images/Nude self portrait - Acrylic on Board -  81cm x 170cm - 2022.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_2nV3pG from "/src/images/Self-Portrait at Firemore- Acrylic on Board - 60cm x 70cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_ZY6Equ from "/src/images/Sandy Macrae - Acrylic on Canvas - 42cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_28UQbq from "/src/images/Margaret Tiller with Self-Portrait - Acrylic on Board -  48cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
import __ASTRO_IMAGE_IMPORT_zcubY from "/src/images/Stewart Macrae with MV Kindat - Acrylic on Board - 60cm x 74cm - 20219.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json";
export default new Map([["/src/images/danmurrayartist-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json", __ASTRO_IMAGE_IMPORT_Z1IIUgz], ["/src/images/danmurrayartist-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json", __ASTRO_IMAGE_IMPORT_LokdX], ["/src/images/skyarts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json", __ASTRO_IMAGE_IMPORT_Z1DezM0], ["/src/images/Jane Seated 2018 Acrylics on board 84cm x 135cm.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_Z1D1O0h], ["/src/images/Andrew Seated - Acrylic on Board - 120cm x 120cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_Z2vgfLz], ["/src/images/Alan with Manson - Acrylic on Board - 84cm x 135cm - 2018.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_1EunyO], ["/src/images/Eleaine - Acrylic on Board - 45cm x 65cm - 2020.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_6nST9], ["/src/images/John and Lyndsay Todd - Acrylic on Board - 91cm x  120cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_Z20dRCP], ["/src/images/Mum in 6 Naast with view to Sron Dubh - Acrylic on Board - 98cm x 170cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_Z5jsxv], ["/src/images/Mum in the afternoon light - Acrylic on Board -  23cm x 30cm - 2025.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_1ipsai], ["/src/images/Nude self portrait - Acrylic on Board -  81cm x 170cm - 2022.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_Z1QqU9G], ["/src/images/Self-Portrait at Firemore- Acrylic on Board - 60cm x 70cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_2nV3pG], ["/src/images/Sandy Macrae - Acrylic on Canvas - 42cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_ZY6Equ], ["/src/images/Margaret Tiller with Self-Portrait - Acrylic on Board -  48cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_28UQbq], ["/src/images/Stewart Macrae with MV Kindat - Acrylic on Board - 60cm x 74cm - 20219.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fportfolio.json", __ASTRO_IMAGE_IMPORT_zcubY]]);
		