
import __ASTRO_IMAGE_IMPORT_Z1IIUgz from "/src/images/danmurrayartist-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json";
import __ASTRO_IMAGE_IMPORT_LokdX from "/src/images/danmurrayartist-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json";
import __ASTRO_IMAGE_IMPORT_Z1DezM0 from "/src/images/skyarts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json";
import __ASTRO_IMAGE_IMPORT_1mBgMC from "/src/images/Alan with Manson - Acrylic on Board - 84cm x 135cm - 2018.JPG?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Falan-with-mason.json";
import __ASTRO_IMAGE_IMPORT_Zat2r from "/src/images/Eleaine - Acrylic on Board - 45cm x 65cm - 2020.JPG?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Feleaine.json";
import __ASTRO_IMAGE_IMPORT_Zrgf0o from "/src/images/Andrew Seated - Acrylic on Board - 120cm x 120cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fandrew-seated.json";
import __ASTRO_IMAGE_IMPORT_ul7TI from "/src/images/Jane Seated 2018 Acrylics on board 84cm x 135cm.JPG?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fjane-seated.json";
import __ASTRO_IMAGE_IMPORT_292OEs from "/src/images/Margaret Tiller with Self-Portrait - Acrylic on Board -  48cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fmargaret-tiller-with-self-portrait.json";
import __ASTRO_IMAGE_IMPORT_Z16k7Ly from "/src/images/John and Lyndsay Todd - Acrylic on Board - 91cm x  120cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fjohn-and-lyndsay-todd.json";
import __ASTRO_IMAGE_IMPORT_2obc72 from "/src/images/Mum in 6 Naast with view to Sron Dubh - Acrylic on Board - 98cm x 170cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fmum-in-6-naast-with-a-view-to-sron-dubh.json";
import __ASTRO_IMAGE_IMPORT_1rcHTF from "/src/images/Mum in the afternoon light - Acrylic on Board -  23cm x 30cm - 2025.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fmum-in-the-afternoon-light.json";
import __ASTRO_IMAGE_IMPORT_ZgvuD5 from "/src/images/Nude self portrait - Acrylic on Board -  81cm x 170cm - 2022.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fnude-self-portrait.json";
import __ASTRO_IMAGE_IMPORT_1lMmc3 from "/src/images/Sandy Macrae - Acrylic on Canvas - 42cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fsandy-macrae.json";
import __ASTRO_IMAGE_IMPORT_ZX9fFQ from "/src/images/Self-Portrait at Firemore- Acrylic on Board - 60cm x 70cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fself-portrait-at-firemore.json";
import __ASTRO_IMAGE_IMPORT_1bq5L5 from "/src/images/Stewart Macrae with MV Kindat - Acrylic on Board - 60cm x 74cm - 20219.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fstewart-macrae-with-mv-kindat.json";
export default new Map([["/src/images/danmurrayartist-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json", __ASTRO_IMAGE_IMPORT_Z1IIUgz], ["/src/images/danmurrayartist-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json", __ASTRO_IMAGE_IMPORT_LokdX], ["/src/images/skyarts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout.json", __ASTRO_IMAGE_IMPORT_Z1DezM0], ["/src/images/Alan with Manson - Acrylic on Board - 84cm x 135cm - 2018.JPG?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Falan-with-mason.json", __ASTRO_IMAGE_IMPORT_1mBgMC], ["/src/images/Eleaine - Acrylic on Board - 45cm x 65cm - 2020.JPG?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Feleaine.json", __ASTRO_IMAGE_IMPORT_Zat2r], ["/src/images/Andrew Seated - Acrylic on Board - 120cm x 120cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fandrew-seated.json", __ASTRO_IMAGE_IMPORT_Zrgf0o], ["/src/images/Jane Seated 2018 Acrylics on board 84cm x 135cm.JPG?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fjane-seated.json", __ASTRO_IMAGE_IMPORT_ul7TI], ["/src/images/Margaret Tiller with Self-Portrait - Acrylic on Board -  48cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fmargaret-tiller-with-self-portrait.json", __ASTRO_IMAGE_IMPORT_292OEs], ["/src/images/John and Lyndsay Todd - Acrylic on Board - 91cm x  120cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fjohn-and-lyndsay-todd.json", __ASTRO_IMAGE_IMPORT_Z16k7Ly], ["/src/images/Mum in 6 Naast with view to Sron Dubh - Acrylic on Board - 98cm x 170cm - 2021.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fmum-in-6-naast-with-a-view-to-sron-dubh.json", __ASTRO_IMAGE_IMPORT_2obc72], ["/src/images/Mum in the afternoon light - Acrylic on Board -  23cm x 30cm - 2025.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fmum-in-the-afternoon-light.json", __ASTRO_IMAGE_IMPORT_1rcHTF], ["/src/images/Nude self portrait - Acrylic on Board -  81cm x 170cm - 2022.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fnude-self-portrait.json", __ASTRO_IMAGE_IMPORT_ZgvuD5], ["/src/images/Sandy Macrae - Acrylic on Canvas - 42cm x 60cm - 2019.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fsandy-macrae.json", __ASTRO_IMAGE_IMPORT_1lMmc3], ["/src/images/Self-Portrait at Firemore- Acrylic on Board - 60cm x 70cm - 2023.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fself-portrait-at-firemore.json", __ASTRO_IMAGE_IMPORT_ZX9fFQ], ["/src/images/Stewart Macrae with MV Kindat - Acrylic on Board - 60cm x 74cm - 20219.jpg?astroContentImageFlag=&importer=src%2Fcontent%2F_portfolio%2Fstewart-macrae-with-mv-kindat.json", __ASTRO_IMAGE_IMPORT_1bq5L5]]);
		