media:
  input: "src/images"
  output: "/images"
content:
  - name: "Works"
    path: "src/content/portfolio.json"
    type: "file"
    list: true
    fields:
      - name: "title"
        type: "string"
        label: "Title"
        required: true
      - name: "medium"
        type: "string"
        label: "Medium"
        required: true
        default: "Acrylic on canvas"
      - name: "Dimensions"
        type: "object"
        fields:
          - name: "width"
            type: "number"
            description: "in centimetres"
            label: "Width"
            required: true
          - name: "height"
            type: "number"
            description: "in centimetres"
            label: "Height"
            required: true
      - name: "year"
        type: "date"
        description: "Don't worry about the day and month, just the year it was finished"
        label: "Year"
        required: true
      - name: "image"
        type: "image"
        label: "Image"
        required: true
      
        
    
    